### ISSUE TITLE
HParams ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by aodhan-domhnaill** [shawwn/gpt-2#15]
Most recent run.

```
Traceback (most recent call last):
  File "./train.py", line 17, in <module>
    import model, sample, encoder
  File "/content/gpt-2/src/model.py", line 3, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

Looks like Tensorflow deprecated Hparams https://github.com/tensorflow/community/issues/148

**Comment by johnpaulbin** [comment]
Before running the training, in colab set your tensorflow version to 1.x:
`%tensorflow_version 1.x`
Much faster than pip install
